services:
  - type: web
    name: libretranslate
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: LT_LOAD_ONLY
        value: en,es,fr
